# Generated by Django 6.0 on 2026-01-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('institucion', models.CharField(max_length=150)),
                ('fecha_obtencion', models.DateField()),
                ('enlace', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('tecnologias', models.CharField(help_text='Ej: Python, Django, PostgreSQL', max_length=200)),
                ('enlace', models.URLField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
