# Generated by Django 4.2.16 on 2026-01-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_usuario', '0002_certificacion_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('institucion', models.CharField(max_length=200)),
                ('fecha_completacion', models.DateField()),
                ('descripcion', models.TextField(blank=True)),
                ('certificado_url', models.URLField(blank=True)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['-fecha_completacion', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Formacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('institucion', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('academica', 'Académica'), ('tecnica', 'Técnica'), ('profesional', 'Profesional')], default='academica', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('actualmente', models.BooleanField(default=False)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Formación',
                'verbose_name_plural': 'Formación',
                'ordering': ['-fecha_inicio', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField()),
                ('url', models.URLField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='garage/')),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Garage',
                'verbose_name_plural': 'Garage',
                'ordering': ['orden', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='MiPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Mi Perfil',
                'verbose_name_plural': 'Mi Perfil',
                'ordering': ['orden', 'fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ProductoLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('proyecto', 'Proyecto'), ('producto', 'Producto'), ('servicio', 'Servicio')], default='proyecto', max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateField()),
                ('url', models.URLField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos_laborales/')),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Producto Laboral',
                'verbose_name_plural': 'Productos Laborales',
                'ordering': ['-fecha_creacion', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Reconocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('institucion', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='reconocimientos/')),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Reconocimiento',
                'verbose_name_plural': 'Reconocimientos',
                'ordering': ['-fecha', 'orden'],
            },
        ),
        migrations.AlterModelOptions(
            name='certificacion',
            options={'ordering': ['-fecha_obtencion', 'orden'], 'verbose_name_plural': 'Certificaciones'},
        ),
        migrations.AlterModelOptions(
            name='experiencia',
            options={'ordering': ['-fecha_inicio', 'orden'], 'verbose_name_plural': 'Experiencias'},
        ),
        migrations.AlterModelOptions(
            name='habilidad',
            options={'ordering': ['orden'], 'verbose_name_plural': 'Habilidades'},
        ),
        migrations.AlterModelOptions(
            name='idioma',
            options={'ordering': ['orden']},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['-fecha', 'orden']},
        ),
        migrations.AddField(
            model_name='certificacion',
            name='orden',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='orden',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='habilidad',
            name='orden',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='idioma',
            name='orden',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='orden',
            field=models.IntegerField(default=0),
        ),
    ]
