# Generated by Django 4.2.16 on 2026-01-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_usuario', '0003_curso_formacion_garage_miperfil_productolaboral_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificacion',
        ),
        migrations.DeleteModel(
            name='Educacion',
        ),
        migrations.DeleteModel(
            name='Formacion',
        ),
        migrations.DeleteModel(
            name='Habilidad',
        ),
        migrations.DeleteModel(
            name='Idioma',
        ),
        migrations.DeleteModel(
            name='MiPerfil',
        ),
        migrations.DeleteModel(
            name='ProductoLaboral',
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['-fecha_fin', '-fecha_inicio'], 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='experiencia',
            options={'ordering': ['-fecha_inicio'], 'verbose_name_plural': 'Experiencias'},
        ),
        migrations.AlterModelOptions(
            name='garage',
            options={'ordering': ['-fecha_publicacion'], 'verbose_name': 'Producto en Garage', 'verbose_name_plural': 'Productos en Garage / Ventas'},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['-fecha'], 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AlterModelOptions(
            name='reconocimiento',
            options={'ordering': ['-fecha'], 'verbose_name_plural': 'Reconocimientos'},
        ),
        migrations.RemoveField(
            model_name='curso',
            name='fecha_completacion',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='experiencia',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='garage',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='garage',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='garage',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='garage',
            name='url',
        ),
        migrations.RemoveField(
            model_name='informacionpersonal',
            name='nombre_completo',
        ),
        migrations.RemoveField(
            model_name='informacionpersonal',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='enlace',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='reconocimiento',
            name='institucion',
        ),
        migrations.RemoveField(
            model_name='reconocimiento',
            name='orden',
        ),
        migrations.AddField(
            model_name='curso',
            name='certificado_file',
            field=models.FileField(blank=True, null=True, upload_to='certificados/cursos/'),
        ),
        migrations.AddField(
            model_name='curso',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='curso',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='mostrar_en_cv',
            field=models.BooleanField(default=True, verbose_name='Mostrar en CV Público'),
        ),
        migrations.AddField(
            model_name='curso',
            name='nombre_contacto',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='curso',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='curso',
            name='total_horas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='certificado_file',
            field=models.FileField(blank=True, null=True, upload_to='certificados/experiencia/'),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Referencia Laboral - Email'),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='email_empresa',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='lugar_empresa',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='mostrar_en_cv',
            field=models.BooleanField(default=True, verbose_name='Mostrar en CV Público'),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='nombre_contacto',
            field=models.CharField(blank=True, max_length=100, verbose_name='Referencia Laboral - Nombre'),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='sitio_web_empresa',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=20, verbose_name='Referencia Laboral - Teléfono'),
        ),
        migrations.AddField(
            model_name='garage',
            name='estado',
            field=models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular')], default='Bueno', max_length=20, verbose_name='Estado del producto'),
        ),
        migrations.AddField(
            model_name='garage',
            name='fecha_publicacion',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de publicación'),
        ),
        migrations.AddField(
            model_name='garage',
            name='mostrar_en_cv',
            field=models.BooleanField(default=True, verbose_name='Mostrar en CV Público'),
        ),
        migrations.AddField(
            model_name='garage',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor del bien ($)'),
        ),
        migrations.AddField(
            model_name='informacionpersonal',
            name='apellidos',
            field=models.CharField(blank=True, max_length=100, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='informacionpersonal',
            name='direccion_domiciliaria',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='informacionpersonal',
            name='direccion_trabajo',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='informacionpersonal',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=50, verbose_name='Estado Civil'),
        ),
        migrations.AddField(
            model_name='informacionpersonal',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informacionpersonal',
            name='licencia_conducir',
            field=models.CharField(blank=True, max_length=20, verbose_name='Licencia de Conducir'),
        ),
        migrations.AddField(
            model_name='informacionpersonal',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Lugar de Nacimiento'),
        ),
        migrations.AddField(
            model_name='informacionpersonal',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='informacionpersonal',
            name='nombres',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombres'),
        ),
        migrations.AddField(
            model_name='informacionpersonal',
            name='numero_cedula',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Número de Cédula'),
        ),
        migrations.AddField(
            model_name='informacionpersonal',
            name='perfil_activo',
            field=models.BooleanField(default=True, verbose_name='Perfil Activo'),
        ),
        migrations.AddField(
            model_name='informacionpersonal',
            name='sexo',
            field=models.CharField(blank=True, choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1),
        ),
        migrations.AddField(
            model_name='informacionpersonal',
            name='sitio_web',
            field=models.URLField(blank=True, verbose_name='Sitio Web Personal'),
        ),
        migrations.AddField(
            model_name='informacionpersonal',
            name='telefono_convencional',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono Convencional'),
        ),
        migrations.AddField(
            model_name='informacionpersonal',
            name='telefono_movil',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono Móvil'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='mostrar_en_cv',
            field=models.BooleanField(default=True, verbose_name='Mostrar en CV Público'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='url',
            field=models.URLField(blank=True, verbose_name='Enlace'),
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='certificado_file',
            field=models.FileField(blank=True, null=True, upload_to='certificados/reconocimientos/'),
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='entidad',
            field=models.CharField(blank=True, max_length=200, verbose_name='Entidad Patrocinadora'),
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='mostrar_en_cv',
            field=models.BooleanField(default=True, verbose_name='Mostrar en CV Público'),
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='nombre_contacto',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Académico', 'Académico'), ('Público', 'Público'), ('Privado', 'Privado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='responsabilidades',
            field=models.TextField(blank=True, verbose_name='Funciones y Responsabilidades'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='garage/', verbose_name='Imagen del producto'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre del producto'),
        ),
        migrations.AlterField(
            model_name='informacionpersonal',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='informacionpersonal',
            name='resumen_profesional',
            field=models.TextField(blank=True, verbose_name='Resumen / Perfil Profesional'),
        ),
        migrations.AlterField(
            model_name='informacionpersonal',
            name='titulo_profesional',
            field=models.CharField(blank=True, max_length=100, verbose_name='Título Profesional'),
        ),
        migrations.AlterField(
            model_name='informacionpersonal',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ubicación / Ciudad'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre del Proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='tecnologias',
            field=models.CharField(blank=True, max_length=300, verbose_name='Tecnologías usadas'),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
